version: '3'
services:
  db:
    image: postgres:latest
    container_name: reddit-db  # 컨테이너 이름 변경
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: '${DB_USER_ID}'
      POSTGRES_PASSWORD: '${DB_USER_PASSWORD}'
    volumes:
      - ./data:/var/lib/postgresql/data
